const designsData = [
  // CLASSIC DESIGNS
  {
    id: "lime-white",
    name: "Lime White",
    scenario: "Classic",
    subScenario: "Original",
    difficulty: null,
    symbol: null,
    dq: null,
    date: null,
    packUnit: null,
    image: "/assets/Lime_White.webp",
    description: "Minimalist and clean design with fresh lime accents."
  },
  {
    id: "orange-dark-red",
    name: "Orange & Dark Red",
    scenario: "Classic",
    subScenario: "Original",
    difficulty: null,
    symbol: null,
    dq: null,
    date: null,
    packUnit: null,
    image: "/assets/Orange_Dark_Red.webp",
    description: "Warm and bold combination of orange and dark red tones."
  },
  {
    id: "pink-yellow",
    name: "Pink & Yellow",
    scenario: "Classic",
    subScenario: "Original",
    difficulty: null,
    symbol: null,
    dq: null,
    date: null,
    packUnit: null,
    image: "/assets/Pink_Yellow.webp",
    description: "Cheerful blend of pink and yellow for a vibrant aesthetic."
  },

  // ADVANCE DESIGNS
  {
    id: "green-valor",
    name: "Green Valor",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "739-479",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Green_Valor.webp",
    description: "Strong and verdant design inspired by nature's power."
  },
  {
    id: "frostline-dare",
    name: "Frostline Dare",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "254-751",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Frostline_Dare.webp",
    description: "Cool and daring design with icy undertones."
  },
  {
    id: "sakura-breeze",
    name: "Sakura Breeze",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "278-133",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Sakura_Breeze.webp",
    description: "Serene cherry blossom inspired aesthetic."
  },
  {
    id: "cozy-pastel",
    name: "Cozy Pastel",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "857-488",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Cozy_Pastel.webp",
    description: "Warm and comfortable pastel color palette."
  },
  {
    id: "ocean-drift",
    name: "Ocean Drift",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "725-715",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Ocean_Drift.webp",
    description: "Calm oceanic theme with flowing transitions."
  },
  {
    id: "pixel-valor",
    name: "Pixel Valor",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "970-464",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Pixel_Valor.webp",
    description: "Retro pixel art inspired design with bold colors."
  },
  {
    id: "desert-ember",
    name: "Desert Ember",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "692-646",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Desert_Ember.webp",
    description: "Warm desert sunset with glowing embers."
  },
  {
    id: "mint-horizon",
    name: "Mint Horizon",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "266-357",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Mint_Horizon.webp",
    description: "Fresh mint colors meeting a peaceful horizon."
  },
  {
    id: "candy-sweet",
    name: "Candy Sweet",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "010-730",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Candy_Sweet.webp",
    description: "Sugary pastel tones for a playful feel."
  },
  {
    id: "midnight-ruins",
    name: "Midnight Ruins",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "[+] Special",
    dq: "346-298",
    date: "101225",
    packUnit: "1-10 (this week)",
    image: "/assets/Midnight_Ruins.webp",
    description: "Dark and mysterious nocturnal aesthetic."
  },
  {
    id: "mint-frost",
    name: "Mint Frost",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "077-568",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Mint_Frost.webp",
    description: "Cool minty design with frosty elements."
  },
  {
    id: "sand-neutral",
    name: "Sand Neutral",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "175-338",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Sand_Natural.webp",
    description: "Earthy and grounded sand-inspired palette."
  },
  {
    id: "cappuccino-cream",
    name: "Cappuccino Cream",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "484-518",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Cappucino_Cream.webp",
    description: "Warm coffee-inspired brown tones."
  },
  {
    id: "soft-lilac",
    name: "Soft Lilac",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "550-228",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Soft_Lilac.webp",
    description: "Gentle and soothing lilac purple shades."
  },
  {
    id: "blue-mist",
    name: "Blue Mist",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "798-779",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Blue_Mist.webp",
    description: "Serene and calming aesthetic with misty blue tones."
  },
  {
    id: "blue-quiet",
    name: "Blue Quiet",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "[+] Special",
    dq: "270-493",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Blue_Quiet.webp",
    description: "Tranquil blue design for peaceful productivity."
  },
  {
    id: "do-green-ever",
    name: "Do Green Ever",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "[+] Special",
    dq: "813-325",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Do_Green_Ever.webp",
    description: "Evergreen design with timeless natural beauty."
  },
  {
    id: "deep-sleep",
    name: "Deep Sleep",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "[÷] Remastered",
    dq: "357-981",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/DeepSleep.webp",
    description: "Dark and restful design for nighttime focus."
  },
  {
    id: "greenary-fields",
    name: "Greenary Fields",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "434-362",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Greenary_Fields.webp",
    description: "Lush green landscape inspired design."
  },
  {
    id: "blue-quiet-advanced",
    name: "Blue Quiet",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "495-409",
    date: "111225",
    packUnit: "1-20 (this week)",
    image: "/assets/Blue_Quiet.webp",
    description: "Quiet blue contemplative space."
  },
  {
    id: "midday-grindline",
    name: "Midday Grindline",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "320-613",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Midnight_Ruins.webp",
    description: "Energetic midday work aesthetic."
  },
  {
    id: "urban-motion-55",
    name: "Urban Motion 55",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "818-607",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Green_Valor.webp",
    description: "Dynamic urban-inspired motion design."
  },
  {
    id: "matrix",
    name: "Matrix",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "579-388",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Pixel_Valor.webp",
    description: "Tech-inspired matrix aesthetic."
  },
  {
    id: "great-rush",
    name: "Great Rush",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "734-039",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Desert_Ember.webp",
    description: "Fast-paced and energetic design."
  },
  {
    id: "chill-crofield",
    name: "Chill Crofield",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "836-812",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Cozy_Pastel.webp",
    description: "Relaxed and chill field aesthetic."
  },
  {
    id: "gridflow-breeze",
    name: "Gridflow Breeze",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "[+] Special",
    dq: "939-862",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Sakura_Breeze.webp",
    description: "Flowing grid-based wind design."
  },
  {
    id: "light-worker-vibes",
    name: "Light Worker Vibes",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "897-058",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Mint_Horizon.webp",
    description: "Inspiring light-filled workspace."
  },
  {
    id: "dawn-calm",
    name: "Dawn Calm",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "771-508",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Ocean_Drift.webp",
    description: "Peaceful dawn awakening design."
  },
  {
    id: "nusantara-daylight",
    name: "Nusantara Daylight",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "[+] Special",
    dq: "557-822",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Green_Valor.webp",
    description: "Tropical daylight inspired design."
  },
  {
    id: "cold-meadow",
    name: "Cold Meadow",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "341-671",
    date: "121225",
    packUnit: "1-30 (this week)",
    image: "/assets/Mint_Frost.webp",
    description: "Cool and crisp meadow landscape."
  },
  {
    id: "cloud-painter",
    name: "Cloud Painter",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "676-399",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Blue_Mist.webp",
    description: "Artistic cloud painting aesthetic."
  },
  {
    id: "still-water",
    name: "Still Water",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "600-384",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Ocean_Drift.webp",
    description: "Serene still water reflection."
  },
  {
    id: "wavering-glower",
    name: "Wavering Glower",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "848-215",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Desert_Ember.webp",
    description: "Gently glowing wave patterns."
  },
  {
    id: "linen-morning",
    name: "Linen Morning",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "303-088",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Sand_Natural.webp",
    description: "Soft linen textured morning light."
  },
  {
    id: "light-routine",
    name: "Light Routine",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "[+] Special",
    dq: "551-499",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Mint_Horizon.webp",
    description: "Daily light-filled routine design."
  },
  {
    id: "soft-start",
    name: "Soft Start",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "972-110",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Cozy_Pastel.webp",
    description: "Gentle beginning for the day."
  },
  {
    id: "open-desk",
    name: "Open Desk",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "717-813",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Blue_Quiet.webp",
    description: "Minimalist open workspace."
  },
  {
    id: "city-flow",
    name: "City Flow",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "General",
    dq: "544-032",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Urban_Motion_55.webp",
    description: "Urban flow and movement."
  },
  {
    id: "task-pressure",
    name: "Task Pressure",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Normal",
    symbol: "[+] Special",
    dq: "219-562",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Green_Valor.webp",
    description: "High-intensity task management."
  },
  {
    id: "core-lock",
    name: "Core Lock",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Hard",
    symbol: "[÷] Remastered",
    dq: "753-919",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Midnight_Ruins.webp",
    description: "Deep focus locked-in state."
  },
  {
    id: "wide-silence",
    name: "Wide Silence",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Peaceful",
    symbol: "General",
    dq: "718-433",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Blue_Mist.webp",
    description: "Expansive peaceful silence."
  },
  {
    id: "ground-flat",
    name: "Ground Flat",
    scenario: "Advance",
    subScenario: "Original",
    difficulty: "Easy",
    symbol: "General",
    dq: "385-168",
    date: "311225",
    packUnit: "1-42 (this week)",
    image: "/assets/Sand_Natural.webp",
    description: "Grounded flat design aesthetic."
  }
];

